#REGISTER USER
# POST http://localhost:3000/api/register
# Accept: application/json
# Content-Type: application/json

# {
#     "name":"Muhammad Iqbal",
#     "email":"mmuhammadiqbal963@gmail.com",
#     "password":"duaenam042000"
# }


# LOGIN USER

# POST http://localhost:3000/api/login
# Accept: application/json
# Content-Type: application/json


# {
#     "email":"mmuhammadiqbal963@gmail.com",
#     "password":"duaenam042000"
# }



#GET PROFILE USER

# GET http://localhost:3000/api/profile
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA0NTQ1NTYsInVzZXJfaWQiOjl9.ngGaLQZyv60XM920OwdbCzvtIPS1BKqWvxPK6O4zwOg
# Content-Type: application/json


#POST VEHICLES

# POST http://localhost:3000/api/vehicles
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA0NTQ1NTYsInVzZXJfaWQiOjl9.ngGaLQZyv60XM920OwdbCzvtIPS1BKqWvxPK6O4zwOg
# Content-Type: application/json

# {
#     "name": "Vario 150",
#     "plate": "BK00VR",
#     "type":"Sepeda Motor",
#     "model":"Honda",
#     "color":"Black"
# }


#GET VEHICLES

# GET http://localhost:3000/api/vehicles/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA0NTQ1NTYsInVzZXJfaWQiOjl9.ngGaLQZyv60XM920OwdbCzvtIPS1BKqWvxPK6O4zwOg
# Content-Type: application/json



#POST GPS VEHICLES

# POST http://localhost:3000/api/gps
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NDIyNzMsInVzZXJfaWQiOjl9.20OJ9wsfHnGdekOJXlwf_4mszdjBlJOmvYOqtNJhS1s
# Content-Type: application/json

# {
#     "vehicle_id": 10,
#     "latitude": 2.800,
#     "longitude": 120.4172,
#     "speed": 200.3
# }

POST http://localhost:3000/api/gps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NDIyNzMsInVzZXJfaWQiOjl9.20OJ9wsfHnGdekOJXlwf_4mszdjBlJOmvYOqtNJhS1s
Content-Type: application/json

{
    "vehicle_id": 11,
    "latitude": 8.1705,
    "longitude": 105.2126,
    "speed": 200.3
}



#GET HISTORY GPS

# GET http://localhost:3000/api/gps/history/11
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA0NTQ1NTYsInVzZXJfaWQiOjl9.ngGaLQZyv60XM920OwdbCzvtIPS1BKqWvxPK6O4zwOg

# GET LAST GPS

# GET http://localhost:3000/api/gps/last/10
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA0NTQ1NTYsInVzZXJfaWQiOjl9.ngGaLQZyv60XM920OwdbCzvtIPS1BKqWvxPK6O4zwOg


#GET STREAM GPS

# GET http://localhost:3000/api/gps/stream/10
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA0NTQ1NTYsInVzZXJfaWQiOjl9.ngGaLQZyv60XM920OwdbCzvtIPS1BKqWvxPK6O4zwOg
