# POST http://localhost:3000/api/login
# Accept: application/json
# Content-Type: application/json

# {
#     "email":"bale@gmail.com",
#     "password":"secret"
# }

# GET  http://localhost:3000/api/protected/test
# Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njk4NTIxMzcsInVzZXJfaWQiOjR9.C0kRmtEpLdFnrUioXBInyg2wNrxiRWFRZ-Mj3P4OhlA

GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njk5NDE1NTgsInVzZXJfaWQiOjV9.eM7GaKYTXuyT6D8E3visZQRmmXuLEm6yLy2qKBj7QZk

# POST http://localhost:3000/api/register
# Accept: application/json
# Content-Type: application/json

# {
#     "name":"bale",
#     "email":"bale@gmail.com",
#     "password":"secret"
# }