// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/iqbal2604/vehicle-tracking-api/config"
	"github.com/iqbal2604/vehicle-tracking-api/handlers"
	"github.com/iqbal2604/vehicle-tracking-api/repositories"
	"github.com/iqbal2604/vehicle-tracking-api/services"
	"github.com/iqbal2604/vehicle-tracking-api/websocket"
)

// Injectors from injector.go:

func InitializeUserHandler() *handlers.UserHandler {
	db := config.NewDatabase()
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler
}

func InitializeVehicleHandler() *handlers.VehicleHandler {
	db := config.NewDatabase()
	vehicleRepository := repositories.NewVehicleRepository(db)
	vehicleService := services.NewVehicleService(vehicleRepository)
	vehicleHandler := handlers.NewVehicleHandler(vehicleService)
	return vehicleHandler
}

func InitializedGPSHandler() *handlers.GPSHandler {
	db := config.NewDatabase()
	gpsRepository := repositories.NewGPSRepository(db)
	vehicleRepository := repositories.NewVehicleRepository(db)
	hub := websocket.NewHub()
	gpsService := services.NewGPSService(gpsRepository, vehicleRepository, hub)
	gpsHandler := handlers.NewGPSHandler(gpsService)
	return gpsHandler
}
