// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/iqbal2604/vehicle-tracking-api/config"
	"github.com/iqbal2604/vehicle-tracking-api/handlers"
	"github.com/iqbal2604/vehicle-tracking-api/logs"
	"github.com/iqbal2604/vehicle-tracking-api/repositories"
	"github.com/iqbal2604/vehicle-tracking-api/services"
	"github.com/iqbal2604/vehicle-tracking-api/websocket"
)

// Injectors from injector.go:

func InitializeUserHandler() *handlers.UserHandler {
	db := config.NewDatabase()
	userRepository := repositories.NewUserRepository(db)
	client := config.NewRedisClient()
	tokenBlacklistRepository := repositories.NewTokenBlacklistRepository(client)
	userService := services.NewUserService(userRepository, tokenBlacklistRepository)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler
}

func InitializeAuthHandler() *handlers.AuthHandler {
	db := config.NewDatabase()
	userRepository := repositories.NewUserRepository(db)
	client := config.NewRedisClient()
	tokenBlacklistRepository := repositories.NewTokenBlacklistRepository(client)
	userService := services.NewUserService(userRepository, tokenBlacklistRepository)
	logRepository := logs.NewLogRepository(db)
	logService := logs.NewLogServiceImpl(logRepository)
	authHandler := handlers.NewAuthHandler(userService, logService)
	return authHandler
}

func InitializeVehicleHandler() *handlers.VehicleHandler {
	db := config.NewDatabase()
	vehicleRepository := repositories.NewVehicleRepository(db)
	vehicleService := services.NewVehicleService(vehicleRepository)
	userRepository := repositories.NewUserRepository(db)
	logRepository := logs.NewLogRepository(db)
	logService := logs.NewLogServiceImpl(logRepository)
	vehicleHandler := handlers.NewVehicleHandler(vehicleService, userRepository, logService)
	return vehicleHandler
}

func InitializedGPSHandler() *GPSComponents {
	db := config.NewDatabase()
	gpsRepository := repositories.NewGPSRepository(db)
	vehicleRepository := repositories.NewVehicleRepository(db)
	hub := websocket.NewHub()
	gpsService := services.NewGPSService(gpsRepository, vehicleRepository, hub)
	userRepository := repositories.NewUserRepository(db)
	logRepository := logs.NewLogRepository(db)
	logService := logs.NewLogServiceImpl(logRepository)
	gpsHandler := handlers.NewGPSHandler(gpsService, userRepository, logService)
	gpsComponents := &GPSComponents{
		Handler: gpsHandler,
		Hub:     hub,
	}
	return gpsComponents
}

func InitializeLogHandler() *logs.LogHandler {
	db := config.NewDatabase()
	logRepository := logs.NewLogRepository(db)
	logService := logs.NewLogServiceImpl(logRepository)
	logHandler := logs.NewLogHandler(logService)
	return logHandler
}

// injector.go:

type GPSComponents struct {
	Handler *handlers.GPSHandler
	Hub     *websocket.Hub
}
